kind: ServiceAccount
apiVersion: v1
metadata:
  name: strimzi-delegator
  namespace: strimzi-operator
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: strimzi-cluster-operator
  namespace: strimzi-operator