kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-rolebinding
  namespace: kafka-test
  labels:
    internal.paas.amadeus.net/sre-ss-control: 'true'
subjects:
  - kind: ServiceAccount
    name: strimzi-delegator
    namespace: strimzi-operator
  - kind: ServiceAccount
    name: strimzi-cluster-operator
    namespace: strimzi-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
