kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: strimzi-cluster-operator-namespaced
  namespace: kafka-test
  labels:
    app: strimzi
subjects:
  - kind: ServiceAccount
    name: strimzi-cluster-operator
    namespace: strimzi-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: strimzi-cluster-operator-namespaced
