apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  annotations:
    kafka.amadeus.com/template.version: 0.29.1-1.0.0
    kafka.amadeus.net/fin-ops-application: MYLAPTOP
    kafka.amadeus.net/region: MINIKUBE
  name: my-upgrade-src
  namespace: kafka-test
  labels:
    acs.amadeus.com/securityZone: app
spec:
  kafka:
    config:
      auto.create.topics.enable: false
      log.message.format.version: '3.0.0'
      message.max.bytes: 1048588
      offsets.topic.replication.factor: 2
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 2
    version: 3.0.0
    template:
      pod:
        metadata:
          annotations:
            acs.amadeus.com/owner: TEC-TPE-PSV-DMB-BIP-KUE
            cmdb.amadeus.net/operated-by: OCKAFKA
            paas.amadeus.net/chorus-path: TEC-TPE-PSV-DMB-BIP-KUE
            paas.amadeus.net/winaproachgroup: OCKAFKA
          labels:
            prometheus.io/scrape-kafka: 'true'
            testing/kafka: tnz
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 200Gi
        deleteClaim: false
    replicas: 2
    resources:
      limits:
        cpu: 800m
        memory: 800Mi
      requests:
        cpu: 400m
        memory: 400Mi
    jvmOptions:
      '-XX':
        MaxMetaspaceFreeRatio: 80
        MetaspaceSize: 96m
        ExplicitGCInvokesConcurrent: true
        G1HeapRegionSize: 16M
        UseG1GC: true
        MinMetaspaceFreeRatio: 50
        PrintGCDetails: true
        InitiatingHeapOccupancyPercent: 35
        MaxGCPauseMillis: 20
      # '-Xms': 1g
      # '-Xmx': 1g
      # '-server': true
      gcLoggingEnabled: false
    listeners:
      - name: external
        port: 9094
        tls: false
        type: loadbalancer
      - name: tls
        port: 9093
        tls: true
        type: internal
  zookeeper:
    replicas: 3
    resources:
      limits:
        cpu: 800m
        memory: 800Mi
      requests:
        cpu: 400m
        memory: 400Mi
    storage:
      type: ephemeral
    template:
      pod:
        metadata:
          annotations:
            acs.amadeus.com/owner: TEC-TPE-PSV-DMB-BIP-KUE
            cmdb.amadeus.net/operated-by: OCKAFKA
            paas.amadeus.net/chorus-path: TEC-TPE-PSV-DMB-BIP-KUE
            paas.amadeus.net/winaproachgroup: OCKAFKA
          labels:
            prometheus.io/scrape-kafka: 'true'
            testing/kafka: tnz
